server.port = 8881
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5433/poouo
spring.datasource.username=postgres
#spring.datasource.url=jdbc:postgresql://db:5432/rshd
#spring.datasource.username=postgres
#spring.datasource.password=1234
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
